/* Even Fibonacci numbers 
* Problem 2 
* Each new term in the Fibonacci sequence is generated by adding the previous two
* terms. By starting with 1 and 2, the first 10 terms will be:
* 
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
*
* By considering the terms in the Fibonacci sequence whose values do not exceed
* four million, find the sum of the even-valued terms.
*
*/

import java.util.ArrayDeque;

public class EvenFibonacci {
    public static void main(String[] args) {
        ArrayDeque<Integer> stack = new ArrayDeque<Integer>(2);
        stack.add(1);
        stack.add(2);

        int sum = 2;

        while(stack.peekLast() < 4000000) {
            stack.addLast(stack.pollFirst() + stack.peekLast());
            if (stack.peekLast() % 2 == 0) {
                sum += stack.peekLast();
            }
        }

        System.out.println("Sum of even Fibonacci sequence numbers < 4mm: " + sum);
    }
}